// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CPUUsage():Promise<string>;

export function DiskUsage():Promise<string>;

export function GetDiskSize():Promise<string>;

export function GetRamUsage():Promise<string>;

export function GetTotalRam():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Test(arg1:string):Promise<string>;
