// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CPUUsage() {
  return window['go']['main']['App']['CPUUsage']();
}

export function DiskUsage() {
  return window['go']['main']['App']['DiskUsage']();
}

export function GetDiskSize() {
  return window['go']['main']['App']['GetDiskSize']();
}

export function GetRamUsage() {
  return window['go']['main']['App']['GetRamUsage']();
}

export function GetTotalRam() {
  return window['go']['main']['App']['GetTotalRam']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}
