// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockUSBPorts():Promise<void>;

export function CPUUsage():Promise<string>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DiskUsage():Promise<string>;

export function GetDiskSize():Promise<string>;

export function GetRamUsage():Promise<string>;

export function GetTotalRam():Promise<string>;

export function GetUSBDevices():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function Test(arg1:string):Promise<string>;

export function UnblockUSBPorts():Promise<void>;
